---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dndtools?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root

server:
  port: 8080
  servlet:
    context-path: /dndtools

logging:
  level:
    org.springframework: WARN
