---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dndtools?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /dndtools
  error:
    include-message: always


logging:
  level:
    org.springframework: WARN
